Type "vim package.json" Enter Sleep 1

Type "5G"
Type "1f1"
Type "r2"

Down
Type "1f0"
Type "r1"
Right 2
Type "r0"

Type "3G"
Type "2f0"
Type "r1"

Type "ZZ" Sleep 1

Type "git add -p"         Enter Sleep 1
Type "y"          Sleep 1 Enter Sleep 1

Type "git commit"          Sleep 1    Enter
Type "i"                   Sleep 0.25
Type "Update dependencies" Sleep 1
Escape
Type "ZZ"                  Sleep 3
