Type "git switch -c feature2" Enter Sleep 1
Type "vim .data"              Enter Sleep 1
Type "14Go"                         Sleep 0.25
Type "SEPARATOR #5.5"         Enter
Type "CHANGE"                       Sleep 1
Escape
Type "ZZ"                           Sleep 1

Type "git add -p"         Enter Sleep 3
Type "y"          Sleep 1 Enter Sleep 1

Type "git commit"   Sleep 1    Enter
Type "i"            Sleep 0.25
Type "Add feature2" Sleep 1
Escape
Type "ZZ"           Sleep 3
